apiVersion: v1
kind: Service
metadata:
  name: dashboard-backend
spec:
  selector:
    app: dashboard-backend
  ports:
    - port: 8000       # port other pods use
      targetPort: 8000 # must match containerPort above